name: Incinerator
main: com.minecraftwars.incinerator.Incinerator
version: 0.0.0.1
authors: [Murder_is_Tasty, squidicuz]
depend: []
softdepend: []

commands:
    risk:
        description: Incinerator help and info
        usage: |
               /incinerator help